
local CONN = Type.Register("Connection", nil, { Table = "connections", Key = "Seq" })
CONN:CreateProperty("Seq", Type.Number, { DatabaseType = "BIGINT", auto_increment = true })
CONN:CreateProperty("Time", Type.DateTime)
CONN:CreateProperty("SteamID", Type.String, { DatabaseType = "VARCHAR(32)" })
CONN:CreateProperty("Name", Type.String, { DatabaseType = "VARCHAR(255)" })
CONN:CreateProperty("IPAddress", Type.String, { DatabaseType = "VARCHAR(32)" })
CONN:CreateProperty("City", Type.String, { DatabaseType = "VARCHAR(255)" })
CONN:CreateProperty("Country", Type.String, { DatabaseType = "VARCHAR(255)" })
CONN:CreateProperty("Timezone", Type.String, { DatabaseType = "VARCHAR(255)" })
CONN:CreateProperty("Longitude", Type.Number)
CONN:CreateProperty("Latitude", Type.Number)
CONN:CreateProperty("Proxy", Type.Boolean)